// // FIREBASE SETUP (one-time, before first build):
// //   1. Create project at console.firebase.google.com
// //   2. Add Android app → download google-services.json → android/app/
// //   3. dart pub global activate flutterfire_cli
// //   4. flutterfire configure  ← generates lib/firebase_options.dart
// //   5. In android/build.gradle add:  classpath 'com.google.gms:google-services:4.4.2'
// //   6. In android/app/build.gradle add at bottom:  apply plugin: 'com.google.gms.google-services'
// //   7. AndroidManifest.xml: add POST_NOTIFICATIONS permission

// import 'package:flutter/material.dart';
// import 'package:flutter/services.dart';
// import 'package:firebase_core/firebase_core.dart';
// import 'package:firebase_crashlytics/firebase_crashlytics.dart';
// import 'firebase_options.dart'; // generated by: flutterfire configure
// import 'services/game_storage.dart';
// import 'services/ad_manager.dart';
// import 'services/achievement_service.dart';
// import 'services/notification_service.dart';
// import 'theme/app_theme.dart';
// import 'screens/splash_screen.dart';

// void main() async {
//   WidgetsFlutterBinding.ensureInitialized();

//   // Firebase core — must come first
//   await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

//   // Route all Flutter framework errors to Crashlytics
//   FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterFatalError;

//   // Route uncaught async/platform errors to Crashlytics
//   // ignore: deprecated_member_use
//   FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterFatalError;

//   await SystemChrome.setPreferredOrientations([
//     DeviceOrientation.portraitUp,
//     DeviceOrientation.portraitDown,
//   ]);

//   await GameStorage.init();
//   await AchievementService.init();
//   await AdManager.initialize();
//   await NotificationService.initialize();

//   runApp(const BrainTwistApp());
// }

// class BrainTwistApp extends StatelessWidget {
//   const BrainTwistApp({super.key});

//   @override
//   Widget build(BuildContext context) {
//     return MaterialApp(
//       title: 'Brain Twist',
//       debugShowCheckedModeBanner: false,
//       theme: AppTheme.theme,
//       home: const SplashScreen(),
//     );
//   }
// }

// FIREBASE SETUP (one-time, before first build):
//   1. Create project at console.firebase.google.com
//   2. Add Android app → download google-services.json → android/app/
//   3. dart pub global activate flutterfire_cli
//   4. flutterfire configure  ← generates lib/firebase_options.dart
//   5. In android/build.gradle add:  classpath 'com.google.gms:google-services:4.4.2'
//   6. In android/app/build.gradle add at bottom:  apply plugin: 'com.google.gms.google-services'
//   7. AndroidManifest.xml: add POST_NOTIFICATIONS permission

import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'firebase_options.dart'; // generated by: flutterfire configure
import 'services/game_storage.dart';
import 'services/ad_manager.dart';
import 'services/achievement_service.dart';
import 'services/notification_service.dart';
import 'theme/app_theme.dart';
import 'screens/splash_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Firebase core — must come first. If this itself fails we still want
  // *some* UI rather than a blank screen, so we guard it too.
  bool firebaseReady = true;
  try {
    await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform);
  } catch (e, st) {
    firebaseReady = false;
    debugPrint('Firebase init failed: $e\n$st');
  }

  if (firebaseReady) {
    // Route uncaught Flutter framework errors to Crashlytics.
    FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterFatalError;

    // Route uncaught async/platform (non-Flutter) errors to Crashlytics too.
    PlatformDispatcher.instance.onError = (error, stack) {
      FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
      return true;
    };
  }

  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  // ── Fault-tolerant service init ─────────────────────────────────────
  // Every one of these used to be a bare `await Foo.init()` with nothing
  // catching failures. If ANY of them threw (e.g. corrupted/unexpected
  // SharedPreferences data left over from a previous run, a stale
  // scheduled-notification id, etc.) the exception propagated out of
  // main() before runApp() was ever called, producing a permanent blank
  // screen on every subsequent cold start — until the user cleared app
  // storage, which wiped out whatever bad value was causing the throw.
  //
  // None of these services should be able to prevent the app from
  // showing its UI. Each is isolated so one bad actor can't take down
  // app startup.
  await _safeInit('GameStorage', GameStorage.init);
  await _safeInit('AchievementService', AchievementService.init);
  await _safeInit('AdManager', AdManager.initialize);
  await _safeInit('NotificationService', NotificationService.initialize);

  runApp(const BrainTwistApp());
}

Future<void> _safeInit(String name, Future<void> Function() init) async {
  try {
    await init();
  } catch (e, st) {
    debugPrint('$name init failed (app will continue without it): $e\n$st');
    try {
      await FirebaseCrashlytics.instance.recordError(
        e,
        st,
        reason: '$name.init() failed during app startup',
        fatal: false,
      );
    } catch (_) {
      // Crashlytics itself may not be ready (e.g. Firebase failed above).
    }
  }
}

class BrainTwistApp extends StatelessWidget {
  const BrainTwistApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Brain Twist',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.theme,
      home: const SplashScreen(),
    );
  }
}
